--Locations
LOCATION_NOTHAND=LOCATION_DECK|LOCATION_REMOVED|LOCATION_GRAVE

--Effects
EFFECT_ELEMENTAL_CONFLUX    			= 2002000130
EFFECT_DOUBLE_FC_TICK 					= 2002000129
EFFECT_REDUCE_FC_COUNT					= 99999999
EFFECT_CAMELLIA_WENDI					= 2002000062+29942771
EFFECT_EXTRA_RITUAL_LOCATION = 2003000079
EFFECT_FUSION_MATERIAL_COUNT = 3003000082
EFFECT_MR3_PENDULUM       = 1000
EFFECT_SUMMONABLE_CARD    = 1001
EFFECT_EQUIPPED_ITSELF    = 1002

--Effect Flags
CUSTOM_LINK_MAT_RESTRICTION          	= 73941492+TYPE_LINK
CUSTOM_ST_SYNCHRO                 		= EFFECT_HAND_SYNCHRO

--Flags to be used with RegisterFlagEffect
MATERIAL_COUNT_LOCATION_FLAG=EFFECT_FUSION_MATERIAL_COUNT+1
MATERIAL_COUNT_FLAG=EFFECT_FUSION_MATERIAL_COUNT+2
ORIGINAL_CARD_UID_FLAG=EFFECT_FUSION_MATERIAL_COUNT+3
PSEUDO_CARD_FLAG=EFFECT_FUSION_MATERIAL_COUNT+4
NOT_PSEUDO_CARD_FLAG=EFFECT_FUSION_MATERIAL_COUNT+5

--Properties
EFFECT_FLAG_GAIN_ONLY_ONE_PER_TURN = 0x20000000

--Flags to be used with Card.RegisterEffect
CUSTOM_REGISTER_FLIP    				= 10
CUSTOM_REGISTER_LIMIT  					= 20
CUSTOM_REGISTER_ZEFRA				    = 30

--Events
EVENT_DECKTOP_CONFIRM              = EVENT_CUSTOM+99912
